/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USER;

import OTHER.DBConnect;
import OTHER.WelcomeScreen;
import OTHER.MailSender;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RG
 */
public class ConfirmedBookingPage extends javax.swing.JFrame {

    String mailToSend = "";
    String emailID = "";

    /**
     * Creates new form bookingConfirmed
     */
    public ConfirmedBookingPage() {
        initComponents();

        TABLE.setBackground(new Color(0, 0, 0, 0));                                 //****************************************
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        TABLE.getTableHeader().setOpaque(false);
        TABLE.getTableHeader().setBackground(new Color(177, 199, 131));
        TABLE.getTableHeader().setFont(new Font("Dubai", Font.PLAIN, 13));
        TABLE.getTableHeader().setBorder(null);
        TABLE.setBackground(new Color(0, 0, 0, 0));
        cellRenderer.setBackground(new Color(129, 129, 129));
        cellRenderer.setForeground(new Color(255, 255, 255));
        jScrollPane1.setBackground(new Color(129, 129, 129));
        jScrollPane1.setOpaque(true);
        TABLE.setOpaque(false);                                                              // Setting Table Properties
        cellRenderer.setOpaque(false);
        TABLE.getColumnModel().getColumn(0).setPreferredWidth(55);
        TABLE.getColumnModel().getColumn(1).setPreferredWidth(80);
        TABLE.getColumnModel().getColumn(2).setPreferredWidth(70);
        TABLE.getColumnModel().getColumn(3).setPreferredWidth(470);
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        TABLE.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        setResizable(false);
        jScrollPane1.setViewportView(TABLE);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);                                                //***************************************

        GreetingMessage.setOpaque(false);
        GreetingMessage.setEditable(false);
        GreetingMessage.setSize(300, 109);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GreetingMessage = new javax.swing.JTextArea();
        GREETINGS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        CHECKOUTDATE = new javax.swing.JLabel();
        CHECKINDATE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONFIRM BOOKINGS | HOTEL MANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreetingMessage.setColumns(20);
        GreetingMessage.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        GreetingMessage.setLineWrap(true);
        GreetingMessage.setRows(5);
        GreetingMessage.setText("Thanks for scheduling with us. We are looking forward to your visit and hope that you enjoy your stay...!!");
        GreetingMessage.setToolTipText("");
        GreetingMessage.setWrapStyleWord(true);
        GreetingMessage.setOpaque(false);
        getContentPane().add(GreetingMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 90));

        GREETINGS.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        GREETINGS.setText("Hi , ");
        getContentPane().add(GREETINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setViewportView(null);

        TABLE.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Type", "Number of Beds", "Room Number", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE.setToolTipText("");
        TABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        TABLE.setFocusable(false);
        TABLE.setGridColor(new java.awt.Color(255, 255, 255));
        TABLE.setIntercellSpacing(new java.awt.Dimension(0, 5));
        TABLE.setOpaque(false);
        TABLE.setRowHeight(23);
        TABLE.setSelectionBackground(new java.awt.Color(133, 133, 133));
        TABLE.setShowGrid(false);
        TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 740, 150));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(178, 199, 132));
        jTextField1.setFont(new java.awt.Font("Dubai", 0, 13)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Check Out Date");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(90, 23));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 110, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(178, 199, 132));
        jTextField3.setFont(new java.awt.Font("Dubai", 0, 13)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Check In Date");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 110, 20));

        CHECKOUTDATE.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        CHECKOUTDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHECKOUTDATE.setText("<DATE>");
        getContentPane().add(CHECKOUTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 100, -1));

        CHECKINDATE.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        CHECKINDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHECKINDATE.setText("<DATE>");
        getContentPane().add(CHECKINDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 100, -1));

        jButton1.setBackground(new java.awt.Color(178, 199, 132));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 20));

        jLabel1.setBackground(new java.awt.Color(177, 199, 131));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel - 2edited.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        setSize(new java.awt.Dimension(814, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new Color(133, 133, 133));
        jButton1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(178, 199, 132));
        jButton1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setBackground(new Color(153, 0, 255));
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jButton1.setBackground(new Color(133, 133, 133));
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MailSender.sendMail(emailID, "Rooms Booked @ HotelMS", mailToSend);
        dispose();
        DBConnect.initialization();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) TABLE.getModel();
        String query1 = "SELECT * FROM USER01.CONFIRMBOOKINGS WHERE "
                + "USERNAME = '" + new DBConnect().getCurrentUser() + "'";

        try {
            ResultSet rs = DBConnect.read("SELECT FIRSTNAME,EMAIL FROM USER01.USERDB "
                    + "WHERE USERID ='" + new DBConnect().getCurrentUser() + "'");                //Setting Greetings
            rs.next();

            emailID = rs.getString("EMAIL");

            GREETINGS.setText("Hi  " + rs.getString("FIRSTNAME") + ",");

            mailToSend += "Dear " + rs.getString("FIRSTNAME") + ",\n";
            mailToSend += "You have booked the following rooms:\n";
            int i = 1;

            ResultSet rs1 = DBConnect.read(query1);                                     //*************************************
            while (rs1.next()) {
                String query2 = "SELECT * FROM USER01.ROOMSDETAILS WHERE "
                        + "ROOMNUMBER = '" + rs1.getString("ROOMNUMBER") + "'";
                ResultSet rs2 = DBConnect.read(query2);
                if (rs2.next()) {
                    model.addRow(new Object[]{rs2.getString("ROOMTYPE"), //Filling Other Details
                        rs2.getString("NUMBEROFBEDS"),
                        rs2.getString("ROOMNUMBER"),
                        rs2.getString("DESCRIPTION")
                    });

                    mailToSend += i + ". " + rs2.getString("ROOMTYPE");
                    if(rs2.getBoolean("DELUXE") == true){
                        mailToSend += " (D)";
                    }
                    mailToSend += "\n";
                    i++;
                }

                CHECKINDATE.setText(rs1.getDate("CHECKINDATE").toString());
                CHECKOUTDATE.setText(rs1.getDate("CHECKOUTDATE").toString());           //**************************************

            }

            mailToSend += "Checkin Date : " + CHECKINDATE.getText() + "\n";
            mailToSend += "Checkout Date : " + CHECKOUTDATE.getText() + "\n";
            mailToSend += "Thank You";

            System.out.println(mailToSend);

            

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowIconified

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLightLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmedBookingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CHECKINDATE;
    private javax.swing.JLabel CHECKOUTDATE;
    private javax.swing.JLabel GREETINGS;
    private javax.swing.JTextArea GreetingMessage;
    private javax.swing.JTable TABLE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
