/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USER;

import OTHER.DBConnect;
import java.awt.Color;
import java.awt.Insets;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

;

/**
 *
 * @author RG
 */
public class UserSupportPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminFeedbackManagingPage
     */
    public UserSupportPage() {
        initComponents();

        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
        TYPEHERE.setMargin(new Insets(12, 12, 12, 12));

        PROBLEMS.getSelectionModel().addListSelectionListener(e -> {
            String complaint = PROBLEMS.getSelectedValue();
            TYPEHERE.setText(complaint);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CHATBOX = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        PROBLEMS = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TYPEHERE = new javax.swing.JTextArea();
        SEND = new javax.swing.JButton();
        GREETINGS = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        SUPPORTFOR = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SUPPORT | HOTELMANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportView(CHATBOX);

        CHATBOX.setEditable(false);
        CHATBOX.setBorder(null);
        CHATBOX.setContentType("text/html"); // NOI18N
        CHATBOX.setToolTipText("");
        CHATBOX.setOpaque(false);
        jScrollPane1.setViewportView(CHATBOX);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 330, 200));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setViewportView(PROBLEMS);

        PROBLEMS.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        PROBLEMS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "I have not recieved my order.", "Items are missing from my order.", "Items are different from what I orderd.", "I have recieved bad quality food.", "The quantity of food is not adequate", "Other than this...." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PROBLEMS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PROBLEMS.setFixedCellHeight(30);
        PROBLEMS.setOpaque(false);
        jScrollPane2.setViewportView(PROBLEMS);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 380, 180));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setViewportView(TYPEHERE);

        TYPEHERE.setColumns(20);
        TYPEHERE.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        TYPEHERE.setLineWrap(true);
        TYPEHERE.setRows(5);
        TYPEHERE.setWrapStyleWord(true);
        TYPEHERE.setBorder(null);
        TYPEHERE.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane3.setViewportView(TYPEHERE);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 290, 140));

        SEND.setBackground(new java.awt.Color(178, 199, 132));
        SEND.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        SEND.setText("SEND");
        SEND.setBorder(null);
        SEND.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SEND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SENDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SENDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SENDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SENDMouseReleased(evt);
            }
        });
        SEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENDActionPerformed(evt);
            }
        });
        getContentPane().add(SEND, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 90, 20));

        GREETINGS.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        GREETINGS.setText("Hi , ");
        getContentPane().add(GREETINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, 30));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(173, 154, 150));
        jTextField6.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Support For");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 20));

        SUPPORTFOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Service", "Room Service", "Entertainment Service", "Bar Service", "Other" }));
        SUPPORTFOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPPORTFORActionPerformed(evt);
            }
        });
        getContentPane().add(SUPPORTFOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel - 2edited.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        setSize(new java.awt.Dimension(814, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SENDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseEntered
        SEND.setBackground(new Color(133, 133, 133));
        SEND.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_SENDMouseEntered

    private void SENDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseExited
        SEND.setBackground(new Color(178, 199, 132));
        SEND.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_SENDMouseExited

    private void SENDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMousePressed
        SEND.setBackground(new Color(153, 0, 255));
    }//GEN-LAST:event_SENDMousePressed

    private void SENDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseReleased
        SEND.setBackground(new Color(133, 133, 133));
    }//GEN-LAST:event_SENDMouseReleased

    private void SENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENDActionPerformed
        String sender = new DBConnect().getCurrentUser();
        String receiver = "Assistant Hotel Manager";
        switch (SUPPORTFOR.getSelectedItem().toString()) {
            case "Food Service":
                receiver = "Executive Chef";
                break;
            case "Room Service":
                receiver = "Housekeeping Supervisor";
                break;
            case "Entertainment Service":
                receiver = "Housekeeping Supervisor";
                break;
            case "Bar Service":
                receiver = "Bar Manager";
                break;
            case "Other":
                receiver = "Assistant Hotel Manager";
                break;
        }

        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String time = new SimpleDateFormat("HH:mm:ss").format(new Date());
        String message = (TYPEHERE.getText() + "\n \n ").replaceAll("\n", "<br/>");

        String query = "INSERT INTO USER01.HELPANDSUPPORT (SENDER, "
                + "RECEIVER, DATE, TIME, SEEN, MESSAGE) VALUES ('"
                + sender + "', '" + receiver
                + "', '" + date + "', '" + time + "', 'false', '" + message + "')";
        try {
            DBConnect.insert(query);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        CHATBOX.setText("");
        String doc = createUHTML.createUHTML();
        CHATBOX.setText(doc);
        TYPEHERE.setText("");
    }//GEN-LAST:event_SENDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ResultSet rs = DBConnect.read("SELECT FIRSTNAME FROM USER01.USERDB "
                    + "WHERE USERID ='" + new DBConnect().getCurrentUser() + "'");                //Setting Greetings
            rs.next();
            GREETINGS.setText("Hi  " + rs.getString("FIRSTNAME") + ",");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        String doc = createUHTML.createUHTML();
        CHATBOX.setText(doc);
    }//GEN-LAST:event_formWindowOpened

    private void SUPPORTFORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPPORTFORActionPerformed
        String sf = SUPPORTFOR.getSelectedItem().toString();
        DefaultListModel<String> model = new DefaultListModel<>();
        PROBLEMS.setModel(model);
        switch (sf) {
            case "Food Service":
                model.removeAllElements();
                model.addElement("I have not recieved my order.");
                model.addElement("Items are missing from my order.");
                model.addElement("Items are different from what I orderd.");
                model.addElement("I have recieved bad quality food.");
                model.addElement("The quantity of food is not adequate.");
                model.addElement("Other than this....");
                break;

            case "Room Service":
                model.removeAllElements();
                model.addElement("Noisy neighbours.");
                model.addElement("Hot water inaccessible.");
                model.addElement("Unsatifactory room cleaning service.");
                model.addElement("Unpleasant Smell in room.");
                model.addElement("Faulty Electronics.");
                model.addElement("Other than this....");
                break;

            case "Entertainment Service":
                model.removeAllElements();
                model.removeAllElements();
                model.addElement("Content Inaccessable.");
                model.addElement("Fake Id and Password.");
                model.addElement("Can not find the remote controller.");
                break;

            case "Bar Service":
                model.removeAllElements();

                break;
            case "Other":
                model.removeAllElements();
                JOptionPane.showMessageDialog(rootPane, "Briefly describe your problem. "
                        + "\n This would help us give you faster solutions.");
                break;
        }
    }//GEN-LAST:event_SUPPORTFORActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        DBConnect.initialization();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSupportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane CHATBOX;
    private javax.swing.JLabel GREETINGS;
    private javax.swing.JList<String> PROBLEMS;
    private javax.swing.JButton SEND;
    private javax.swing.JComboBox<String> SUPPORTFOR;
    private javax.swing.JTextArea TYPEHERE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
