/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

/**
 *
 * @author DADDY
 */
public class signupForm extends javax.swing.JFrame {

    /**
     * Creates new form signupForm
     */
    public signupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        SIGNUP = new javax.swing.JLabel();
        FIRSTNAME = new javax.swing.JLabel();
        NAMEIDX = new javax.swing.JTextField();
        LASTNAME = new javax.swing.JLabel();
        NAMEIDX2 = new javax.swing.JTextField();
        USERNAME = new javax.swing.JLabel();
        USERNAMEIDX = new javax.swing.JTextField();
        PASS = new javax.swing.JLabel();
        PASSIDX = new javax.swing.JTextField();
        REPASS = new javax.swing.JLabel();
        REPASSIDX = new javax.swing.JTextField();
        EMAIL = new javax.swing.JLabel();
        EMAILIDX = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        IDOPTIONIDX = new javax.swing.JComboBox<>();
        ADDRESS = new javax.swing.JLabel();
        ADDRESSIDX = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MOBILENUM = new javax.swing.JLabel();
        MOBILEIDX = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        CHECKBOX = new javax.swing.JCheckBox();
        REGISTERBUTTON = new javax.swing.JButton();
        EXITBUTTON = new javax.swing.JButton();
        LOGINLINK = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        WALLPAER = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SIGNUP.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        SIGNUP.setForeground(new java.awt.Color(255, 255, 255));
        SIGNUP.setText("SIGN UP");
        jPanel1.add(SIGNUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        FIRSTNAME.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        FIRSTNAME.setForeground(new java.awt.Color(255, 255, 255));
        FIRSTNAME.setText("FIRST NAME");
        jPanel1.add(FIRSTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        NAMEIDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEIDXActionPerformed(evt);
            }
        });
        jPanel1.add(NAMEIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        LASTNAME.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        LASTNAME.setForeground(new java.awt.Color(255, 255, 255));
        LASTNAME.setText("LAST NAME");
        jPanel1.add(LASTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 30));
        jPanel1.add(NAMEIDX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 30));

        USERNAME.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        USERNAME.setText("USERNAME");
        jPanel1.add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));
        jPanel1.add(USERNAMEIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 209, 130, 30));

        PASS.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        PASS.setForeground(new java.awt.Color(255, 255, 255));
        PASS.setText("PASSWORD");
        jPanel1.add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, 30));

        PASSIDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSIDXActionPerformed(evt);
            }
        });
        jPanel1.add(PASSIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 160, 30));

        REPASS.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        REPASS.setForeground(new java.awt.Color(255, 255, 255));
        REPASS.setText("RE-TYPE PASSWORD *");
        jPanel1.add(REPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        jPanel1.add(REPASSIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 200, 30));

        EMAIL.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EMAIL.setForeground(new java.awt.Color(255, 255, 255));
        EMAIL.setText("E-MAIL ADDRESS ");
        jPanel1.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 30));

        EMAILIDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILIDXActionPerformed(evt);
            }
        });
        jPanel1.add(EMAILIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 200, 30));

        ID.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID-PROOF");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        IDOPTIONIDX.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        IDOPTIONIDX.setMaximumRowCount(4);
        IDOPTIONIDX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DRIVING LICENCE", "PASSPORT", "AADHAR CARD", "VOTER ID" }));
        IDOPTIONIDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDOPTIONIDXActionPerformed(evt);
            }
        });
        jPanel1.add(IDOPTIONIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 200, 30));

        ADDRESS.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        ADDRESS.setForeground(new java.awt.Color(255, 255, 255));
        ADDRESS.setText("ADDRESS ");
        jPanel1.add(ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        ADDRESSIDX.setViewportView(jTextArea1);

        jPanel1.add(ADDRESSIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 320, 70));

        MOBILENUM.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        MOBILENUM.setForeground(new java.awt.Color(255, 255, 255));
        MOBILENUM.setText("MOBILE NUMBER");
        jPanel1.add(MOBILENUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        jPanel1.add(MOBILEIDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 369, 200, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 90, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 352, 120, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 70, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 70, 20));

        CHECKBOX.setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        CHECKBOX.setForeground(new java.awt.Color(255, 255, 255));
        CHECKBOX.setText("I ACCEPT THE FOLLOWING TERMS AND CONDITION*");
        CHECKBOX.setBorder(null);
        CHECKBOX.setOpaque(false);
        jPanel1.add(CHECKBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 240, -1));

        REGISTERBUTTON.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        REGISTERBUTTON.setText("REGISTER");
        REGISTERBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTERBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, -1, -1));

        EXITBUTTON.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        EXITBUTTON.setText("EXIT");
        EXITBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITBUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(EXITBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, -1, -1));

        LOGINLINK.setBackground(new java.awt.Color(255, 255, 255));
        LOGINLINK.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        LOGINLINK.setForeground(new java.awt.Color(255, 255, 0));
        LOGINLINK.setText("CLICK HERE TO LOGIN");
        LOGINLINK.setBorder(null);
        LOGINLINK.setBorderPainted(false);
        LOGINLINK.setOpaque(false);
        LOGINLINK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINLINKActionPerformed(evt);
            }
        });
        jPanel1.add(LOGINLINK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 130, 20));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 130, 10));

        WALLPAER.setIcon(new javax.swing.ImageIcon("C:\\Users\\DADDY\\Downloads\\FHOTEL.png")); // NOI18N
        jPanel1.add(WALLPAER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 572, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEIDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEIDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEIDXActionPerformed

    private void PASSIDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSIDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSIDXActionPerformed

    private void IDOPTIONIDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDOPTIONIDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDOPTIONIDXActionPerformed

    private void LOGINLINKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINLINKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINLINKActionPerformed

    private void REGISTERBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBUTTONActionPerformed
       String email=EMAILIDX.getText();
       String fname=NAMEIDX.getName();
       String lname=NAMEIDX2.getName();
       String passw=PASSIDX.getName();
       String UNAME=USERNAMEIDX.getName();
       String fnmae=NAMEIDX.getName();
       String fnmae=NAMEIDX.getName();
       String fnmae=NAMEIDX.getName();
       String fnmae=NAMEIDX.getName();
       
    }//GEN-LAST:event_REGISTERBUTTONActionPerformed

    private void EXITBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITBUTTONActionPerformed

    private void EMAILIDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILIDXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILIDXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDRESS;
    private javax.swing.JScrollPane ADDRESSIDX;
    private javax.swing.JCheckBox CHECKBOX;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JTextField EMAILIDX;
    private javax.swing.JButton EXITBUTTON;
    private javax.swing.JLabel FIRSTNAME;
    private javax.swing.JLabel ID;
    private javax.swing.JComboBox<String> IDOPTIONIDX;
    private javax.swing.JLabel LASTNAME;
    private javax.swing.JButton LOGINLINK;
    private javax.swing.JTextField MOBILEIDX;
    private javax.swing.JLabel MOBILENUM;
    private javax.swing.JTextField NAMEIDX;
    private javax.swing.JTextField NAMEIDX2;
    private javax.swing.JLabel PASS;
    private javax.swing.JTextField PASSIDX;
    private javax.swing.JButton REGISTERBUTTON;
    private javax.swing.JLabel REPASS;
    private javax.swing.JTextField REPASSIDX;
    private javax.swing.JLabel SIGNUP;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JTextField USERNAMEIDX;
    private javax.swing.JLabel WALLPAER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
