/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SPARSH
 */
public class welcomeScreen2 extends javax.swing.JFrame {

    /**
     * Creates new form welcomeScreen
     */
    public welcomeScreen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roomBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        bookRoomBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        welcomeLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Management System");

        jPanel1.setForeground(background.getForeground());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setBackground(new java.awt.Color(111, 63, 220));
        mainLabel.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(111, 63, 220));
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Hotel Management System");
        jPanel1.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 570, 70));

        jSeparator1.setBackground(new java.awt.Color(111, 63, 220));
        jSeparator1.setForeground(new java.awt.Color(111, 63, 220));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 570, 40));

        roomBtn.setBackground(jPanel1.getBackground());
        roomBtn.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        roomBtn.setForeground(new java.awt.Color(255, 255, 255));
        roomBtn.setText("Room Prices");
        roomBtn.setBorder(null);
        roomBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roomBtn.setOpaque(false);
        jPanel1.add(roomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, 50));

        aboutBtn.setBackground(jPanel1.getBackground());
        aboutBtn.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About Us");
        aboutBtn.setBorder(null);
        aboutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutBtn.setOpaque(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 190, 50));

        signOutBtn.setBackground(jPanel1.getBackground());
        signOutBtn.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        signOutBtn.setText("Sign Out");
        signOutBtn.setBorder(null);
        signOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutBtn.setOpaque(false);
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 190, 50));

        bookRoomBtn.setBackground(jPanel1.getBackground());
        bookRoomBtn.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        bookRoomBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookRoomBtn.setText("Book Room");
        bookRoomBtn.setBorder(null);
        bookRoomBtn.setBorderPainted(false);
        bookRoomBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookRoomBtn.setOpaque(false);
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, 50));

        welcomeLabel.setFont(new java.awt.Font("Dubai", 0, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 51, 0));
        welcomeLabel.setText(getUserName(new DBConnect().getCurrentUser()));
        jPanel1.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 420, 50));

        welcomeLabel1.setFont(new java.awt.Font("Dubai", 0, 36)); // NOI18N
        welcomeLabel1.setForeground(new java.awt.Color(51, 51, 0));
        welcomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel1.setText("Welcome, ");
        jPanel1.add(welcomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel - 1.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new DBConnect().setCurrentUser("");
        DBConnect.initialization();
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRoomBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomeScreen2().setVisible(true);
            }
        });
    }
    
    private static String getUserName(String userid){
        String name = "";
        String SQL = "SELECT FIRSTNAME, LASTNAME FROM USER01.USERDB WHERE USERID = ?";
        Connection con = new DBConnect().DBCon();
        try {
            PreparedStatement stmt = con.prepareStatement(SQL);
            stmt.setString(1, userid);
            ResultSet rs = stmt.executeQuery();
            rs.next();
            name = rs.getString("FIRSTNAME");
            name = name + " " + rs.getString("LASTNAME");
        } 
        catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return name;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JLabel background;
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton roomBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel1;
    // End of variables declaration//GEN-END:variables
}
