/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OTHER;

import OTHER.DBConnect;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RG
 */
public class RoomsDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form roomsDetails
     */
    public RoomsDetailsPage() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        King = new javax.swing.JLabel();
        MiniSuite = new javax.swing.JLabel();
        Queen = new javax.swing.JLabel();
        Single = new javax.swing.JLabel();
        PresidentialSuite = new javax.swing.JLabel();
        Suite = new javax.swing.JLabel();
        Double = new javax.swing.JLabel();
        Studio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ROOM DETAILS | HOTEL MANAGEMENT SYSTEM");
        setResizable(false);
        setSize(new java.awt.Dimension(620, 452));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(620, 452));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        King.setBackground(new java.awt.Color(129, 129, 129));
        King.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        King.setForeground(new java.awt.Color(255, 255, 255));
        King.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        King.setText("King");
        King.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        King.setPreferredSize(new java.awt.Dimension(300, 250));
        King.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KingMouseExited(evt);
            }
        });
        jPanel1.add(King, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        MiniSuite.setBackground(new java.awt.Color(129, 129, 129));
        MiniSuite.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        MiniSuite.setForeground(new java.awt.Color(255, 255, 255));
        MiniSuite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MiniSuite.setText("Mini-Suite");
        MiniSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniSuite.setPreferredSize(new java.awt.Dimension(300, 250));
        MiniSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniSuiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MiniSuiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MiniSuiteMouseExited(evt);
            }
        });
        jPanel1.add(MiniSuite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Queen.setBackground(new java.awt.Color(129, 129, 129));
        Queen.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Queen.setForeground(new java.awt.Color(255, 255, 255));
        Queen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Queen.setText("Qween");
        Queen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Queen.setPreferredSize(new java.awt.Dimension(300, 250));
        Queen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QueenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QueenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QueenMouseExited(evt);
            }
        });
        jPanel1.add(Queen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        Single.setBackground(new java.awt.Color(129, 129, 129));
        Single.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Single.setForeground(new java.awt.Color(255, 255, 255));
        Single.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Single.setText("Single");
        Single.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Single.setPreferredSize(new java.awt.Dimension(300, 250));
        Single.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SingleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SingleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SingleMouseExited(evt);
            }
        });
        jPanel1.add(Single, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        PresidentialSuite.setBackground(new java.awt.Color(129, 129, 129));
        PresidentialSuite.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        PresidentialSuite.setForeground(new java.awt.Color(255, 255, 255));
        PresidentialSuite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PresidentialSuite.setText("Presidential-Suite");
        PresidentialSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PresidentialSuite.setPreferredSize(new java.awt.Dimension(300, 250));
        PresidentialSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresidentialSuiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PresidentialSuiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PresidentialSuiteMouseExited(evt);
            }
        });
        jPanel1.add(PresidentialSuite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        Suite.setBackground(new java.awt.Color(129, 129, 129));
        Suite.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Suite.setForeground(new java.awt.Color(255, 255, 255));
        Suite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Suite.setText("Suite");
        Suite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Suite.setPreferredSize(new java.awt.Dimension(300, 250));
        Suite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SuiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SuiteMouseExited(evt);
            }
        });
        jPanel1.add(Suite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        Double.setBackground(new java.awt.Color(129, 129, 129));
        Double.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Double.setForeground(new java.awt.Color(255, 255, 255));
        Double.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Double.setText("Double");
        Double.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Double.setPreferredSize(new java.awt.Dimension(300, 250));
        Double.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoubleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoubleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoubleMouseExited(evt);
            }
        });
        jPanel1.add(Double, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 750, -1, -1));

        Studio.setBackground(new java.awt.Color(129, 129, 129));
        Studio.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Studio.setForeground(new java.awt.Color(255, 255, 255));
        Studio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Studio.setText("Studio");
        Studio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Studio.setPreferredSize(new java.awt.Dimension(300, 250));
        Studio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudioMouseExited(evt);
            }
        });
        jPanel1.add(Studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/roomdetails.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 1000));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(634, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MiniSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniSuiteMouseEntered
        MiniSuite.setBackground(new Color(129, 129, 129));
        MiniSuite.setOpaque(true);
    }//GEN-LAST:event_MiniSuiteMouseEntered

    private void MiniSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniSuiteMouseExited
        MiniSuite.setOpaque(false);
    }//GEN-LAST:event_MiniSuiteMouseExited

    private void KingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KingMouseEntered
        King.setBackground(new Color(129, 129, 129));
        King.setOpaque(true);
    }//GEN-LAST:event_KingMouseEntered

    private void KingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KingMouseExited
        King.setOpaque(false);
    }//GEN-LAST:event_KingMouseExited

    private void QueenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueenMouseEntered
        Queen.setBackground(new Color(129, 129, 129));
        Queen.setOpaque(true);
    }//GEN-LAST:event_QueenMouseEntered

    private void QueenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueenMouseExited
        Queen.setOpaque(false);
    }//GEN-LAST:event_QueenMouseExited

    private void SingleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingleMouseEntered
        Single.setBackground(new Color(129, 129, 129));
        Single.setOpaque(true);
    }//GEN-LAST:event_SingleMouseEntered

    private void SingleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingleMouseExited
        Single.setOpaque(false);
    }//GEN-LAST:event_SingleMouseExited

    private void SuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuiteMouseEntered
        Suite.setBackground(new Color(129, 129, 129));
        Suite.setOpaque(true);
    }//GEN-LAST:event_SuiteMouseEntered

    private void SuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuiteMouseExited
        Suite.setOpaque(false);
    }//GEN-LAST:event_SuiteMouseExited

    private void PresidentialSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresidentialSuiteMouseEntered
        PresidentialSuite.setBackground(new Color(129, 129, 129));
        PresidentialSuite.setOpaque(true);
    }//GEN-LAST:event_PresidentialSuiteMouseEntered

    private void PresidentialSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresidentialSuiteMouseExited
        PresidentialSuite.setOpaque(false);
    }//GEN-LAST:event_PresidentialSuiteMouseExited

    private void DoubleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleMouseEntered
        Double.setBackground(new Color(129, 129, 129));
        Double.setOpaque(true);
    }//GEN-LAST:event_DoubleMouseEntered

    private void DoubleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleMouseExited
        Double.setOpaque(false);
    }//GEN-LAST:event_DoubleMouseExited

    private void StudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudioMouseEntered
        Studio.setBackground(new Color(129, 129, 129));
        Studio.setOpaque(true);
    }//GEN-LAST:event_StudioMouseEntered

    private void StudioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudioMouseExited
        Studio.setOpaque(false);
    }//GEN-LAST:event_StudioMouseExited

    private void MiniSuiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniSuiteMouseClicked
        MiniSuite.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA single room with a "
            + "bed and\n sitting area. Size upto 100m².\n\n*Price :  Rs. 3099");
    }//GEN-LAST:event_MiniSuiteMouseClicked

    private void KingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KingMouseClicked
        King.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA room with a "
                + "king-sized bed.\n The room size or area of King \nRooms are "
                + "upto 50 m².\n\n*Price :  Rs. 1599 |  Rs. 1799[D]");
    }//GEN-LAST:event_KingMouseClicked

    private void QueenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueenMouseClicked
        Queen.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA room with a "
                + "queen-sized bed.\n The room size or area of Queen \nRooms are "
                + "upto 50 m².\n\n*Price :  Rs. 1299 |  Rs. 1499[D]");
    }//GEN-LAST:event_QueenMouseClicked

    private void SingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingleMouseClicked
        Single.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA room assigned "
                + "to one person \nhave one bed. The room size or \narea of Single"
                + " Room is 40 m².\n\n*Price :  Rs. 699 |  Rs. 799[D]");
    }//GEN-LAST:event_SingleMouseClicked

    private void PresidentialSuiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresidentialSuiteMouseClicked
       PresidentialSuite.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nThe most expensive"
               + " room provided by us.\nWith three king-sized bedrooms. Upto "
               + "350m².\n\n*Price :  Rs. 6999");
    }//GEN-LAST:event_PresidentialSuiteMouseClicked

    private void SuiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuiteMouseClicked
        Suite.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA parlour or "
                + "living room connected \nwith to one or more bedrooms. \nSize "
                + "upto 100m².\n\n*Price :  Rs. 3099");
    }//GEN-LAST:event_SuiteMouseClicked

    private void DoubleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoubleMouseClicked
        Double.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA room assigned "
                + "to two people \nhave two bed. The room size or area of \nDouble"
                + " Rooms is 50 m².\n\n*Price :  Rs. 899 | Rs. 999[D]");
    }//GEN-LAST:event_DoubleMouseClicked

    private void StudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudioMouseClicked
        Studio.setBackground(new Color(153, 0, 255));
        JOptionPane.showMessageDialog(rootPane, "Description :  \nA room with a "
                + "studio bed- a couch \nwhich can be converted into a bed.\n\n"
                + "*Price :  Rs. 2099");
    }//GEN-LAST:event_StudioMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        DBConnect.initialization();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomsDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomsDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomsDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomsDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomsDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Double;
    private javax.swing.JLabel King;
    private javax.swing.JLabel MiniSuite;
    private javax.swing.JLabel PresidentialSuite;
    private javax.swing.JLabel Queen;
    private javax.swing.JLabel Single;
    private javax.swing.JLabel Studio;
    private javax.swing.JLabel Suite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
