/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import OTHER.DBConnect;
import OTHER.WelcomeScreen;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RG
 */
public class AdminSearchByUserID extends javax.swing.JFrame {

    /**
     * Creates new form bookingConfirmed
     */
    public AdminSearchByUserID() {
        initComponents();

        TABLE.setBackground(new Color(0, 0, 0, 0));
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        TABLE.getTableHeader().setOpaque(false);
        TABLE.getTableHeader().setBackground(new Color(177, 199, 131));
        TABLE.getTableHeader().setFont(new Font("Dubai", Font.PLAIN, 13));
        TABLE.getTableHeader().setBorder(null);
        TABLE.setBackground(new Color(0, 0, 0, 0));
        cellRenderer.setBackground(new Color(129, 129, 129));
        cellRenderer.setForeground(new Color(255, 255, 255));
        jScrollPane1.setBackground(new Color(129, 129, 129));
        jScrollPane1.setOpaque(true);
        TABLE.setOpaque(false);
        cellRenderer.setOpaque(false);

        TABLE.getColumnModel().getColumn(0).setPreferredWidth(55);
        TABLE.getColumnModel().getColumn(1).setPreferredWidth(80);
        TABLE.getColumnModel().getColumn(2).setPreferredWidth(70);
        TABLE.getColumnModel().getColumn(3).setPreferredWidth(470);
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        TABLE.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        TABLE.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        setResizable(false);
        jScrollPane1.setViewportView(TABLE);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);

        jTextArea1.setOpaque(false);
        jTextArea1.setEditable(false);
        jTextArea1.setSize(250, 90);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        GREETINGS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        CHECKOUTDATE = new javax.swing.JLabel();
        CHECKINDATE = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        GUESTID = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        NAME = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN | HOTEL MANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ask the guest for his phone number to proceed..");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 70));

        GREETINGS.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        GREETINGS.setText("Hi , ");
        getContentPane().add(GREETINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setViewportView(null);

        TABLE.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Type", "Number of Beds", "Room Number", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLE.setToolTipText("");
        TABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        TABLE.setFocusable(false);
        TABLE.setGridColor(new java.awt.Color(255, 255, 255));
        TABLE.setIntercellSpacing(new java.awt.Dimension(0, 5));
        TABLE.setOpaque(false);
        TABLE.setRowHeight(23);
        TABLE.setSelectionBackground(new java.awt.Color(133, 133, 133));
        TABLE.setShowGrid(false);
        TABLE.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 740, 150));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(178, 199, 132));
        jTextField1.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Check Out Date");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(90, 23));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(178, 199, 132));
        jTextField3.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Check In Date");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 110, 20));

        CHECKOUTDATE.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        CHECKOUTDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHECKOUTDATE.setText("<DATE>");
        getContentPane().add(CHECKOUTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 120, -1));

        CHECKINDATE.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        CHECKINDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHECKINDATE.setText("<DATE>");
        getContentPane().add(CHECKINDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 120, -1));

        OK.setBackground(new java.awt.Color(178, 199, 132));
        OK.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        OK.setText("OK");
        OK.setBorder(null);
        OK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                OKMouseReleased(evt);
            }
        });
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 20));

        GUESTID.setFont(new java.awt.Font("Dubai", 0, 13)); // NOI18N
        GUESTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GUESTID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        GUESTID.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                GUESTIDCaretUpdate(evt);
            }
        });
        GUESTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUESTIDActionPerformed(evt);
            }
        });
        getContentPane().add(GUESTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, 20));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(173, 154, 150));
        jTextField6.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Guest's ID");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, 20));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(173, 154, 150));
        jTextField7.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Guest's Name");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 110, 20));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(173, 154, 150));
        jTextField8.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Guest's E-mail");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, 20));

        NAME.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NAME.setText("<NAME>");
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 110, -1));

        EMAIL.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        EMAIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EMAIL.setText("<E-Mail>");
        getContentPane().add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 120, -1));

        jLabel1.setBackground(new java.awt.Color(177, 199, 131));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel - 2edited.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        setSize(new java.awt.Dimension(814, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseEntered
        OK.setBackground(new Color(133, 133, 133));
        OK.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_OKMouseEntered

    private void OKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseExited
        OK.setBackground(new Color(178, 199, 132));
        OK.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_OKMouseExited

    private void OKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMousePressed
        OK.setBackground(new Color(153, 0, 255));
    }//GEN-LAST:event_OKMousePressed

    private void OKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKMouseReleased
        OK.setBackground(new Color(133, 133, 133));
    }//GEN-LAST:event_OKMouseReleased

    private void GUESTIDCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_GUESTIDCaretUpdate
        String user_id = GUESTID.getText();
        DefaultTableModel model = (DefaultTableModel) TABLE.getModel();
        
        NAME.setText("<Name>");
        EMAIL.setText("<E-Mail>");
        CHECKINDATE.setText("<Check In Date>");
        CHECKOUTDATE.setText("<Check Out Date>");
        
        model.setRowCount(0);                                                       // Removing previously added rows if any
        
        try{
            String query1 = "SELECT * FROM USER01.USERDB WHERE USERID = '"+ user_id +"'";
            ResultSet rs1 = DBConnect.read(query1);
            if(rs1.next()){                                                             //Filling Guest's Details.
                NAME.setText(rs1.getString("FIRSTNAME") + " " + 
                        rs1.getString("LASTNAME"));
                EMAIL.setText(rs1.getString("EMAIL"));
            
                String query2 = "SELECT * FROM USER01.CONFIRMBOOKINGS WHERE USERNAME = '"+ user_id +"'";
                ResultSet rs2 = DBConnect.read(query2);
                int c = 0;
                while(rs2.next()){                                                         //Filling Guest's Details.
                    c++;
                    String query3 = "SELECT * FROM USER01.ROOMSDETAILS WHERE "
                        + "ROOMNUMBER = '"+ rs2.getString("ROOMNUMBER") +"'";
                    ResultSet rs3 = DBConnect.read(query3);
                    if(rs3.next()){                                                      //Addding data in table about rooms booked by guest
                        model.addRow(new Object[]{rs3.getString("ROOMTYPE"),
                                           rs3.getString("NUMBEROFBEDS"),
                                           rs3.getString("ROOMNUMBER"),
                                           rs3.getString("DESCRIPTION")
                    });
                    }
                    CHECKINDATE.setText(rs2.getDate("CHECKINDATE").toString());         
                    CHECKOUTDATE.setText(rs2.getDate("CHECKOUTDATE").toString());
            
                }
                if(c==0){
                    CHECKINDATE.setText("Not Booked Any Room");         
                    CHECKOUTDATE.setText("Not Booked Any Room");
                
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_GUESTIDCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            ResultSet rs = DBConnect.read("SELECT FIRSTNAME FROM "
                    + "USER01.ADMINDB WHERE USERID ='" + 
                    new DBConnect().getCurrentUser() + "'");                        // Setting up Greetings
            rs.next();
            GREETINGS.setText("Hi  " + rs.getString("FIRSTNAME") + ",");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
        DBConnect.initialization();
    }//GEN-LAST:event_formWindowClosed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        dispose();
        DBConnect.initialization();
    }//GEN-LAST:event_OKActionPerformed

    private void GUESTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUESTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUESTIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLightLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearchByUserID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CHECKINDATE;
    private javax.swing.JLabel CHECKOUTDATE;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel GREETINGS;
    private javax.swing.JTextField GUESTID;
    private javax.swing.JLabel NAME;
    private javax.swing.JButton OK;
    private javax.swing.JTable TABLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
