/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import OTHER.DBConnect;
import java.awt.Color;
import java.awt.Insets;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RG
 */
public class AdminSupportPage extends javax.swing.JFrame {
    static List senderid = new ArrayList();
    static List sendername = new ArrayList();
    static String admintitle;
    /**
     * Creates new form AdminFeedbackManagingPage
     */
    public AdminSupportPage() {
        initComponents();
        
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
        TYPEHERE.setMargin(new Insets(12, 12, 12, 12));
        
        CHATS.getSelectionModel().addListSelectionListener(e -> {
            ResultSet rs1 = DBConnect.read("SELECT * FROM USER01.ADMINDB "
                    + "WHERE USERID ='" + new DBConnect().getCurrentUser() + "'");
            ResultSet rs2 = DBConnect.read("SELECT * FROM USER01.USERDB "
                    + "WHERE USERID ='" + senderid.get(sendername.indexOf(CHATS.getSelectedValue())).toString() + "'");
            try{
                rs1.next();
                admintitle = rs1.getString("TITLE");
                rs2.next();
                NAME.setText(rs2.getString("FIRSTNAME") + " " + rs2.getString("LASTNAME"));
                EMAIL.setText(rs2.getString("EMAIL"));
                ID.setText(rs2.getString("MOBILENUMBER"));
                CHATBOX.setText("");
                createAHTML.setTitle(admintitle);
                createAHTML.setReceiver(senderid.get(sendername.indexOf(CHATS.getSelectedValue())).toString());
                String doc = createAHTML.createAHTML();
                CHATBOX.setText(doc);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            TYPEHERE.setEditable(true);
            SEND.setEnabled(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CHATBOX = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        CHATS = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TYPEHERE = new javax.swing.JTextArea();
        SEND = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        NAME = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        EMAIL = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        GREETINGS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SUPPORT | HOTEL MANAGEMENT SYSTEM");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewportView(CHATBOX);

        CHATBOX.setEditable(false);
        CHATBOX.setBorder(null);
        CHATBOX.setContentType("text/html"); // NOI18N
        CHATBOX.setToolTipText("");
        CHATBOX.setOpaque(false);
        jScrollPane1.setViewportView(CHATBOX);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 360, 290));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setViewportView(CHATS);

        CHATS.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        CHATS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CHATS.setOpaque(false);
        jScrollPane2.setViewportView(CHATS);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 290, 140));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setViewportView(TYPEHERE);

        TYPEHERE.setColumns(20);
        TYPEHERE.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        TYPEHERE.setLineWrap(true);
        TYPEHERE.setRows(5);
        TYPEHERE.setWrapStyleWord(true);
        TYPEHERE.setBorder(null);
        TYPEHERE.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane3.setViewportView(TYPEHERE);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 290, 140));

        SEND.setBackground(new java.awt.Color(178, 199, 132));
        SEND.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        SEND.setText("SEND");
        SEND.setBorder(null);
        SEND.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SEND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SENDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SENDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SENDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SENDMouseReleased(evt);
            }
        });
        SEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENDActionPerformed(evt);
            }
        });
        getContentPane().add(SEND, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, 20));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(173, 154, 150));
        jTextField6.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Mobile Number");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 110, 20));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(173, 154, 150));
        jTextField7.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Guest's Name");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 110, 20));

        NAME.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NAME.setText("<NAME>");
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 120, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(173, 154, 150));
        jTextField8.setFont(new java.awt.Font("Dubai", 1, 13)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Guest's E-mail");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 110, 20));

        EMAIL.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        EMAIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EMAIL.setText("<E-NUMBER>");
        getContentPane().add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 120, -1));

        ID.setFont(new java.awt.Font("Dubai", 2, 12)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID.setText("<MOBILE NUMBER>");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 120, -1));

        GREETINGS.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        GREETINGS.setText("Hi , ");
        getContentPane().add(GREETINGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Hotel - 2edited.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        setSize(new java.awt.Dimension(814, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SENDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseEntered
        SEND.setBackground(new Color(133, 133, 133));
        SEND.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_SENDMouseEntered

    private void SENDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseExited
        SEND.setBackground(new Color(178, 199, 132));
        SEND.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_SENDMouseExited

    private void SENDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMousePressed
        SEND.setBackground(new Color(153, 0, 255));
    }//GEN-LAST:event_SENDMousePressed

    private void SENDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENDMouseReleased
        SEND.setBackground(new Color(133, 133, 133));
    }//GEN-LAST:event_SENDMouseReleased

    private void SENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENDActionPerformed
        String sender = admintitle;
        String receiver = senderid.get(sendername.indexOf(CHATS.getSelectedValue())).toString();
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String time = new SimpleDateFormat("HH:mm:ss").format(new Date());
        String message = (TYPEHERE.getText() + "\n \n ").replaceAll("\n", "<br/>");
        
        String query = "INSERT INTO USER01.HELPANDSUPPORT (SENDER, "
                                + "RECEIVER, DATE, TIME, SEEN, MESSAGE) VALUES ('"
                                + sender + "', '" + receiver
                                + "', '" + date + "', '" + time + "', 'false', '" + message + "')";
        try{
            DBConnect.insert(query);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        CHATBOX.setText("");
        createAHTML.setTitle(admintitle);
        createAHTML.setReceiver(senderid.get(sendername.indexOf(CHATS.getSelectedValue())).toString());
        String doc = createAHTML.createAHTML();
        CHATBOX.setText(doc);
        TYPEHERE.setText("");
    }//GEN-LAST:event_SENDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel<String> model = new DefaultListModel<>();
        CHATS.setModel(model);
        try{
            ResultSet rs1 = DBConnect.read("SELECT * FROM USER01.ADMINDB "
                    + "WHERE USERID ='" + new DBConnect().getCurrentUser() + "'");                //Setting Greetings
            rs1.next();
            GREETINGS.setText("Hi  " + rs1.getString("FIRSTNAME") + ",");
            
            ResultSet rs2 = DBConnect.read("SELECT * FROM USER01.HELPANDSUPPORT "
                    + "WHERE RECEIVER='"+ rs1.getString("TITLE") +"' ORDER BY DATE, TIME DESC");
            while(rs2.next()){
                if(!senderid.contains(rs2.getString("SENDER"))){
                    senderid.add(rs2.getString("SENDER"));
                }
            }
            for(int i=0; i<senderid.size(); i++){
                ResultSet rs3 = DBConnect.read("SELECT * FROM USER01.USERDB WHERE USERID ='" + senderid.get(i).toString() + "'");
                if(rs3.next()){
                    model.addElement(rs3.getString("FIRSTNAME") + " " + rs3.getString("LASTNAME"));
                    sendername.add(rs3.getString("FIRSTNAME") + " " + rs3.getString("LASTNAME"));
                }
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        TYPEHERE.setEditable(false);
        SEND.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
        DBConnect.initialization();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSupportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane CHATBOX;
    private javax.swing.JList<String> CHATS;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel GREETINGS;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel NAME;
    private javax.swing.JButton SEND;
    private javax.swing.JTextArea TYPEHERE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
